services:
  - type: web
    runtime: ruby
    name: Valenti-Cleaners-POS # the name of this service, eg hello-world
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: Valenti-Cleaners-POS
          property: connectionString
databases: # this section provides some additional database configuration
  - name: Valenti-Cleaners-POS
    plan: free
    databaseName: valenti_cleaners_pos
    user: valenti_cleaners_pos_user
    ipAllowList: []
