services:
  - type: web
    runtime: ruby
    name: Valenti-Cleaners-POS 
    plan: free 
    buildCommand: "./bin/render-build.sh" 
    startCommand: "./bin/render-start.sh"
    envVars: 
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: Valenti-Cleaners-POS
          property: connectionString
databases: 
  - name: Valenti-Cleaners-POS
    plan: free
    databaseName: valenti_cleaners_pos
    user: valenti_cleaners_pos_user
    ipAllowList: []
